// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/pluralize/pluralize.d.ts
interface PluralizeStatic {
    /**
     * Pluralize or singularize a word based on the passed in count.
     *
     * @param word
     * @param count
     * @param inclusive
     */
    (word: string, count?: number, inclusive?: boolean): string;

    /**
     * Pluralize a word based.
     *
     * @param word
     */
    plural(word: string): string;

    /**
     * Singularize a word based.
     *
     * @param word
     */
    singular(word: string): string;

    /**
     * Add a pluralization rule to the collection.
     *
     * @param rule
     * @param replacement
     */
    addPluralRule(rule: string|RegExp, replacemant: string): void;

    /**
     * Add a singularization rule to the collection.
     *
     * @param rule
     * @param replacement
     */
    addSingularRule(rule: string|RegExp, replacemant: string): void;

    /**
     * Add an irregular word definition.
     *
     * @param single
     * @param plural
     */
    addIrregularRule(single: string, plural: string): void;

    /**
     * Add an uncountable word rule.
     *
     * @param word
     */
    addUncountableRule(word: string|RegExp): void;
}

declare module "pluralize" {
    export = pluralize;
}
declare var pluralize: PluralizeStatic;
